//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKursad.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        public int urunid { get; set; }
        public string urunbaslik { get; set; }
        public string urunresim { get; set; }
        public string urunfiyat { get; set; }
        public string urunkategori { get; set; }
    }
}
